### ISSUE TITLE
Support continuous multioutput targets

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/scikit-learn-knn#13]
This ties in to #2, but I think is going to need its own issue to track: now that we're planning on passing the target data (e.g. composition) directly in as `y`, subclassing from `KNeighborsClassifier` no longer works because it doesn't support continuous multioutput targets. For example:

```python
clf = Mahalanobis()
X = [[0, 1], [1, 1], [2, 2], [3, 3]]  # environmental features
y = [[0.1, 0.2], [0.2, 0.3], [0.3, 0.4], [0.4, 0.5]]  # composition targets
clf.fit(X, y)

ValueError: Unknown label type: 'continuous-multioutput'
```

The easiest solution is to subclass `KNeighborsRegressor` instead, which supports continuous multioutput targets. This will break the current `kneighbor_ids` implementation which relies on the `classes_` attribute that doesn't exist on regressors, but I think that was going to need to be modified regardless based our discussion on handling plot IDs. There might be other side effects to this change I haven't considered...

The other option would be to patch continuous multioutput support into a subclass of `KNeighborsClassifier`, and subclass the rest of our estimators from that instead. This sort of gets back to #6 and the question of whether we're going to consider our estimators as regressors, classifiers, or something in between.

Let me know what you think!

**Comment by grovduck** [comment]
Definitely tied to #2!  But I'm fairly confident that your first instinct is the best here - we subclass from `KNeighborsRegressor` instead of `KNeighborsClassifier`.  Even in the case of `k=1`, `KNeighborsRegressor` will behave correctly as that first neighbor will have full weight.  

I think the proposed changes in #2 gets rid of `kneighbors_ids` altogether and, because in our current implementation, the `classes_` attribute is actually the IDs and we'll be switching that to be stored in a different property, we won't need `classes_`.  (I know that you're a few steps ahead of me, but helpful for me to type it out).  

And I do think this helps clarify #6 a bit as well and they will more naturally fit as regressors from a `sklearn` viewpoint.  I'm always a bit squeamish with thinking about nearest neighbors as "regression" per se, because I'm more used to thinking about *parametric* regression (e.g. ordinary least-squares regression), but I think the term in technically correct in a non-parametric sense (at least it's first on the list of non-parametric regression methods in Wikipedia!).

**Comment by grovduck** [comment]
> What do you think about me pushing forward with a quick PR to swap `KNeighborsClassifier` for `KNeighborsRegressor` and remove `kneighbor_ids`? We would need to temporarily disable the part of the tests that use `kneighbor_ids` until we finalize whether/how we're going to handle IDs, but it seems like this might untangle at least one thread that would make it easier to move ahead with implementing #2.

Definitely in favor.  I agree we'll have issues with tests, but I think this will help clarify the path forward.  (BTW, Friday was a mess of a day trying to get `MSN` ported.  Apparently R and numpy use different Fortran packages to do matrix decomposition which lead to different answers.  I haven't pushed anything yet and will just stash my changes for now until we get this resolved.)

**Comment by aazuspan** [comment]
> Apparently R and numpy use different Fortran packages to do matrix decomposition which lead to different answers.

Yikes, that sounds like a headache! Is it just floating point error that's close enough for an `array_almost_equal` check, or is it actually going to lead to different results?

**Comment by grovduck** [comment]
>  Is it just floating point error that's close enough for an `array_almost_equal` check, or is it actually going to lead to different results?

Right now, the latter.  But I think it's likely my lack of knowledge on the approaches (QR decomposition in LINPACK vs LAPACK) rather than true substantive differences.  This decomposition is just a intermediate step, so it's possible that the resulting transformation is fine - I plan to dig back in today.
