### ISSUE TITLE
Set up dev tools

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/scikit-learn-knn#4]
- [x] Formatting
- [x] Linting
- [x] Type-checking
- [x] Pre-commit
- [x] CI

**Comment by aazuspan** [comment]
@grovduck Any thoughts on Python version support? I'm setting up [tox](https://tox.wiki/en/latest/) and need to figure out which environments to test against, but we don't currently list a `python_requires` in `setup.py`. 

I usually loosely follow the [numpy support schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html), which just dropped `3.8` a few days ago, but that seems a bit strict. `sklearn` still supports `>=3.8`. Any preferences?

**Comment by grovduck** [comment]
@aazuspan, this will start sounding repetitive, but I'll trust your judgement on this.  A couple of random thoughts to consider, but probably not too strongly:

- It's possible that we might have ArcGIS users that aren't too familiar with Python and would therefore use the Python that ships with ArcGIS Pro.  The default is a conda virtual environment using Python 3.9.
- When thinking about typing, it's really nice to just use `list`, `dict`, etc. and that came in at 3.9?  We'd have to import `Typing` otherwise, correct?  I'm guessing you know clever tricks around this.

At first blush, it seems to be reasonable to follow what `sklearn` supports, so I'm OK with 3.8.

**Comment by aazuspan** [comment]
Good thought on the ArcGIS constraint! I hadn't considered that.

I agree that following `sklearn`'s lead here makes sense. Adding a `from __future__ import annotations` gives access to typing with built-ins as early as `3.7` (see [PEP 585](https://peps.python.org/pep-0585/#implementation)), so I think we should be good to go with `3.8`!
